config/routes.rb
AssignFive::Application.routes.draw do
root "users#index"
  resources :users do
    resources :posts
  end
  get "/search" => "home#search"
  get "/sessions/new" => "sessions#new"
  post "/sessions/new" => "sessions#create"
  delete "/sessions" => "sessions#destroy", as: :logout  

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	if session[:user_id]
  		User.find(session[:user_id])
  	else 
  		nil
  	end

  	helper_method :current_user
end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def search
		@users = User.where(fname: params[:query])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    # @posts = Post.where(user_id: params[:user_id])
  end

  def show
    @post = Post.find(params[:id]) #Couldn't find Post with id=post_id
    
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Post #{@post.title} deleted successfully!"
      redirect_to user_posts_path(@post.user)
    else
      flash[:alert] = "there was a problem destroying #{@post.title}"
      redirect_to :back
    end
    
  end

  def new 
    @post = Post.new
    @user = User.find(params[:user_id])
  end

  def create #process data and actual create a new record 
    @post = Post.new(params[:post])
    @post.user_id = params[:user_id] #Associate post to a specific user 
    if @post.save
      flash[:notice] = "Your Post was created
      successfully."
      redirect_to user_post_path(@post.user, @post) #Instant of User and of the post 
    else
      flash[:alert] = "There was a problem saving your
      Post."
      redirect_to new_user_post_path(@post.user)
    end
  end 

  def edit # enter in the new info in a form 
    @post = Post.find(params[:id]) #Can infer user 

  end

  def update  #process data and update user record 
    @post = Post.find(params[:id]) #REMEMBER   .where returns an array we want the .first one even if there is only one
    if @post.update_attributes(params[:post])
      flash[:notice] = "Your account was updated
      successfully."
    else
      flash[:alert] = "There was a problem saving your
      account."
    end
    redirect_to user_post_path(@post.user, @post)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.where(email: params[:email]).first
		if @user && @user.password == params[:password]
			session[:user_id] = @user.id
			flash[:notice] = "you are logged in"
			redirect_to user_path(@user)
		else
			flash[:alert] = "there was a problem"
			redirect_to root_path

		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "you were logged out"
		redirect_to user_path(@user)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id]) 
  end

  def destroy
    @user = User.where(id: params[:id]).first#.destroy
    if @user && @user.destroy
      flash[:notice] = "User #{@user.fname} #{@user.lname} deleted successfully!"
    else
      flash[:alert] = "there was a problem destroying #{@user.fname}"
    end
    redirect_to root_path
  end

  def new # enter in the new info in a form 
    @user = User.new
  end 

  def create #process data and actual create a new record, 
    @user = User.new(user_params) # create a new instance of user  
    
    if @user.save
      flash[:notice] = "Your account was created
      successfully."
      redirect_to root_path 
    else
      flash[:alert] = "There was a problem saving your
      account."
      redirect_to new_user_path
    end
  end 

  def edit # enter in the new info in a form 
    @user = User.find(params[:id]) 
  end

  def update  #process data and update user record 
    @user = User.where(id: params[:id]).first #REMEMBER   .where returns an array we want the .first one even if there is only one
    if @user.update_attributes(params[:user])
      flash[:notice] = "Your account was updated
      successfully."
      redirect_to user_path(@user) 
    else
      flash[:alert] = "There was a problem saving your
      account."
      redirect_to new_user_path #or :back to go back to where u just came from 
    end
  end

  private
    def user_params
      params.require(:user).permit(:fname, :lname, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/search.html.erb
<h1>Search Page</h1>
<nav>
  <li><%=link_to "Home", root_path%></li>
  <li><%=link_to "Sign Up", new_user_path%></li>
  <li>Log In</li>
  <li><%=link_to "Search", search_path%></li>
</nav>

<br>

Search for a user here 

<%=form_tag "/search", method: :get do %>
  <%=label_tag :query, "Search:" %>
  <%=text_field_tag :query %>
  <%=submit_tag :submit  %>
<% end %>
  
  <% if @users %>
  	<% @users.each do |user| %>
  	  <%=user.fname %>
    	<br>
    	<br>
    <% end%>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assign_5</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:notice] %>
		<div class="flash notice">
		<%=flash[:notice] %>
		</div>
	<% end %>

	<% if flash[:alert] %>
		<div class="flash notice">
		<%=flash[:alert] %>
		</div>
	<% end %>
     <!-- %=link_to "Log Out", logout_path, method: :delete) if current_user % -->
<%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<%=post.title%>
<br>
<%=post.created_at%>
<br>
<%=link_to "Profile", user_path(params[:user_id])%>

app/views/posts/edit.html.erb
<h1>Edit Profile</h1>
<nav>
  <li><%=link_to "Home", root_path%></li>
  <li><%=link_to "Sign Up", new_user_path%></li>
  <li>Log In</li>
  <li><%=link_to "Search", search_path%></li>
</nav>
<br>

<%=form_for [@post.user, @post], html: {method: :put} do |f| %>
  <%=f.label :title, "Title" %>
  <%=f.text_field :title %>
  <br>
  <%=f.submit "Update Post"%>
 <%end%>

app/views/posts/index.html.erb
<h1>Posts</h1>
<nav>
	<li><%=link_to "Home", root_path%></li>
	<li><%=link_to "Sign Up", new_user_path%></li>
	<li>Log In</li>
	<li><%=link_to "Search", search_path%></li>
</nav>
<br>

<div>
	<% @user.posts.each do |post| %>
	  <%=post.title %>
	  <br>
	  <%=post.created_at.strftime("%b %d, %Y") %>
	  <br>
	  <%=link_to "This Post", user_post_path(post.user, post) %> <!--??-->
	  <br>
	  <br>
	<!--   %=link_to "Delete Post", user_posts_path(params[:id]), method: :delete % -->
	<% end %>
</div>

<%=link_to "User Profile", user_path(params[:user_id])%>

app/views/posts/new.html.erb
<h1>Create a New Post</h1>
<nav>
	<li><%=link_to "Home", root_path%></li>
	<li><%=link_to "Sign Up", new_user_path%></li>
	<li>Log In</li>
	<li><%=link_to "Search", search_path%></li>
</nav>
<br>

<%=form_for [@user, @post] do |f| %> <!--undefined method `posts_path' RAILS assumes its not a nested resource-->
	<%=f.label :title, "Title" %>
 	<%=f.text_field :title %>
 	<br>
 	<%=f.submit "Post It!" %> 
<% end %>

app/views/posts/show.html.erb
<h1>Specific Post</h1>
<nav>
	<li><%=link_to "Home", root_path%></li>
	<li><%=link_to "Sign Up", new_user_path%></li>
	<li>Log In</li>
	<li><%=link_to "Search", search_path%></li>
</nav>
<br>

<%=render "post", post: @post %>

<%=link_to "Edit this", edit_user_post_path(@post.user, @post)%>

<%=link_to "Delete this", user_post_path(@post.user, @post), method: :delete%>

app/views/users/_user.html.erb
First Name: <%=user.fname%> 
<br>
Last Name: <%=user.lname%>
<br>
Email: <%=user.email%>
<br>
<%=link_to "Posts", user_posts_path(user.id)%>
<%=link_to "Profile", user_path(user.id)%>
<br>
<br>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<nav>
  <li><%=link_to "Home", root_path%></li>
  <li><%=link_to "Sign Up", new_user_path%></li>
  <li>Log In</li>
  <li><%=link_to "Search", search_path%></li>
</nav>
<br>

<%= form_for @user, html: {method: :put} do |f| %>
  <%=f.label :fname, "First Name" %>
  <%=f.text_field :fname %>
  <br>
  <%=f.label :lname, "Last Name" %>
  <%=f.text_field :lname %>
  <br>
  <%=f.label :email, "Email" %>
  <%=f.text_field :email %>
  <br>
  <%=f.label :password, "Password"%>
  <%=f.password_field :password %>
  <br>
  <%=f.submit :update %>
<% end %><h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Here is a list of users</h1>
<nav>
	<li><%=link_to "Home", root_path%></li>
	<li><%=link_to "Sign Up", new_user_path%></li>
	<li>Log In</li>
	<li><%=link_to "Search", search_path%></li>
</nav>
<br>

<div>
<% @users.each do |user| %>
	<%=render "user", user: user %>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<nav>
  <li><%=link_to "Home", root_path%></li>
  <li><%=link_to "Sign Up", new_user_path%></li>
  <li>Log In</li>
  <li><%=link_to "Search", search_path%></li>
</nav>
<br>

<%= form_for @user do |f| %>
  <%=f.label :fname, "First Name" %>
  <%=f.text_field :fname %>
  <br>
  <%=f.label :lname, "Last Name" %>
  <%=f.text_field :lname %>
  <br>
  <%=f.label :email, "Email" %>
  <%=f.text_field :email %>
  <br>
  <%=f.label :password, "Password" %>
  <%=f.password_field :password %>
  <br> 
  <%=f.submit :create %> 
  <!-- OR you can use a string bc submit doesnt take a form -->
<% end %>

app/views/users/show.html.erb
<h1>Here Is Your Profile</h1>
<nav>
	<li><%=link_to "Home", root_path%></li>
	<li><%=link_to "Sign Up", new_user_path%></li>
	<li>Log In</li>
	<li><%=link_to "Search", search_path%></li>
</nav>
<br>

<%=render "user", user: @user %>

<%=link_to "Edit Profile", edit_user_path%>

<%=link_to "Delete User", user_path(params[:id]), method: :delete %>